# Generated by Django 6.0.4 on 2026-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_logical', models.IntegerField(default=0)),
                ('min_linguistic', models.IntegerField(default=0)),
                ('min_spatial', models.IntegerField(default=0)),
                ('min_interpersonal', models.IntegerField(default=0)),
                ('min_intrapersonal', models.IntegerField(default=0)),
                ('min_naturalist', models.IntegerField(default=0)),
                ('min_bodily', models.IntegerField(default=0)),
                ('min_musical', models.IntegerField(default=0)),
                ('careers', models.ManyToManyField(to='api.career')),
            ],
        ),
    ]
