# Generated by Django 6.0.4 on 2026-04-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(default='[]'),
        ),
    ]
